# Site settings
## Change the values as needed.
title: ReReCassandra
email: rere.cassandra.project@gmail.com
description: "Re:Reading Re:Writing Cassandra"
keywords: "jekyll, theme, material, muicss"
#url: "http://bitwiser.in/bitwiser-material" # the base hostname & protocol for your site
url: "https://rerecassandra.github.io/" # the base hostname & protocol for your site
baseurl: "" # the subpath of your site, e.g. /blog/
paginate: 5
paginate_path: "page:num"
# Build settings
markdown: kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: :compressed
links:
  facebook: RereCassandra
  instagram: rere.cassandra
  email: rere.cassandra.project@gmail.com
  github: ReReCassandra
exclude:
  - bower_components
  - README.md
full_name: ReReCassandra

##set this to enable disqus commenting
# disqus: bitwiser

##set this to enable google analytics
#ga_id: analyticsID
#ga_domain: bitwiser.in
